[package]
name = "container-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
nix = "0.29.0"
serde = { version = "1.0.204", features = ["serde_derive"] }
serde_json = "1.0.120"
strum = "0.26.3"
strum_macros = "0.26.4"
